### ISSUE TITLE
two "fxa-checkbox__box-outline" elements added

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-checkbox#2]
<img width="448" alt="screen shot 2015-10-05 at 16 00 38" src="https://cloud.githubusercontent.com/assets/848085/10284128/58735616-6b7a-11e5-8cf3-4fcb8e67a7cb.png">

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/fxa-checkbox/commit/4172fe01302bf757f8c5635103d04da8072ae47f
