### ISSUE TITLE
Reduce checkbox hit area

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-checkbox#7]
The hit area of the checkbox currently include the box graphic itself, the label text, and the box padding - basically everything within this rectangle:

![screen shot 2016-02-24 at 09 26 37](https://cloud.githubusercontent.com/assets/34695/13269018/bb894c96-dad9-11e5-9e35-629d1d1acf9f.png)

@ryanfeeley notes we should narrow it to checkbox itself, the space between the checkbox and the label, and the label text.

**Comment by ryanfeeley** [comment]
Please change the title. Not just the box, the text too (just not the space to the right of it)

**Comment by larissagaulia** [comment]
Hi @rfk, could you point me to the page where this is happening, so I can take a look, please?

**Comment by vladikoff** [comment]
@larissagaulia To have quick access to that view locally do this:
- Change code in `app/scripts/views/choose_what_to_sync.js`, comment out the signup check:

``` diff
diff --git a/app/scripts/views/choose_what_to_sync.js b/app/scripts/views/choose_what_to_sync.js
index a980741..f19f6df 100644
--- a/app/scripts/views/choose_what_to_sync.js
+++ b/app/scripts/views/choose_what_to_sync.js
@@ -32,10 +32,10 @@ define(function (require, exports, module) {

     beforeRender: function () {
       // user cannot proceed if they have not initiated a sign up/in.
-      if (! this.getAccount().get('sessionToken')) {
-        this.navigate('signup');
-        return false;
-      }
+      // if (! this.getAccount().get('sessionToken')) {
+      //   this.navigate('signup');
+      //   return false;
+      // }
     },

     context: function () {
```
- Open http://127.0.0.1:3030/choose_what_to_sync?context=fx_desktop_v2&service=sync

You should then see:

![](http://v14d.com/i/56ef839b39349.jpg)

To edit styles: run `grunt sass watch` in a terminal tab in the `fxa-content-server` directory

Let us know if you need help!

**Comment by TDA** [comment]
Fixed in fxa-content-server PR: https://github.com/mozilla/fxa-content-server/pull/3759/.
Closing.
